---
- name: download ssl keys from S3
  amazon.aws.s3_object:
    mode: get
    object: '{{ ssl_sync_s3_dir }}/{{ item }}.key'
    dest: '{{ ssl_sync_dir }}/{{ item }}.key'
    endpoint_url: '{{ ssl_sync_s3_credentials.s3_url }}'
    region: '{{ ssl_sync_s3_credentials.region }}'
    bucket: '{{ ssl_sync_s3_credentials.bucket }}'
    access_key: '{{ ssl_sync_s3_credentials.aws_access_key }}'
    secret_key: '{{ ssl_sync_s3_credentials.aws_secret_key }}'
  with_items: '{{ ssl_sync_domains }}'
  when: ssl_sync_download_keys | default(True) | bool

- name: download ssl certificate from S3
  amazon.aws.s3_object:
    mode: get
    object: '{{ ssl_sync_s3_dir }}/{{ item }}.crt'
    dest: '{{ ssl_sync_dir }}/{{ item }}.crt'
    endpoint_url: '{{ ssl_sync_s3_credentials.s3_url }}'
    region: '{{ ssl_sync_s3_credentials.region }}'
    bucket: '{{ ssl_sync_s3_credentials.bucket }}'
    access_key: '{{ ssl_sync_s3_credentials.aws_access_key }}'
    secret_key: '{{ ssl_sync_s3_credentials.aws_secret_key }}'
  with_items: '{{ ssl_sync_domains }}'
  when: ssl_sync_download_certificates | default(True) | bool

- name: download ssl certificate fullchains from S3
  amazon.aws.s3_object:
    mode: get
    object: '{{ ssl_sync_s3_dir }}/{{ item }}-fullchain.crt'
    dest: '{{ ssl_sync_dir }}/{{ item }}-fullchain.crt'
    endpoint_url: '{{ ssl_sync_s3_credentials.s3_url }}'
    region: '{{ ssl_sync_s3_credentials.region }}'
    bucket: '{{ ssl_sync_s3_credentials.bucket }}'
    access_key: '{{ ssl_sync_s3_credentials.aws_access_key }}'
    secret_key: '{{ ssl_sync_s3_credentials.aws_secret_key }}'
  with_items: '{{ ssl_sync_domains }}'
  when: ssl_sync_download_certificate_fullchains | default(True) | bool

- name: download ssl certificate bundles from S3
  amazon.aws.s3_object:
    mode: get
    object: '{{ ssl_sync_s3_dir }}/{{ item }}-bundle.pem'
    dest: '{{ ssl_sync_dir }}/{{ item }}-bundle.pem'
    endpoint_url: '{{ ssl_sync_s3_credentials.s3_url }}'
    region: '{{ ssl_sync_s3_credentials.region }}'
    bucket: '{{ ssl_sync_s3_credentials.bucket }}'
    access_key: '{{ ssl_sync_s3_credentials.aws_access_key }}'
    secret_key: '{{ ssl_sync_s3_credentials.aws_secret_key }}'
  with_items: '{{ ssl_sync_domains }}'
  when: ssl_sync_download_certificate_bundles | default(True) | bool
